version: '3.8'
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
     - "8000:8000"
    environment:
      DETA_PROJECT_KEY: "${DETA_PROJECT_KEY}"
      MONGODB_URL: "${MONGODB_URL}"
      TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
      TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
      TWILIO_PHONE_NUMBER: "${TWILIO_PHONE_NUMBER}"
      SMTP_PASSOWORD: "${SMTP_PASSOWORD}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_ALGORITHM: "${JWT_ALGORITHM}"