name: Deploy to Deta
on: push
env:
  DETA_TOKEN: AS9tbuj2_5GZYsK2NYEvYrtAAXAtp5uNk4PTjAavN

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: "$DETA_TOKEN"
          deta-name: "api"
          deta-project: "centarnit"
